language: node_js
sudo: false
node_js:
  - 8
python:
  - 3
install:
  - npm install
  # `awscli` is required for invalidation of CloudFront distributions.
  - pip install awscli
script: PUBLIC_URL=. npm run-script build
deploy:
  provider: s3
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: "makerdao.com"
  acl: public_read
  local-dir: build
  upload-dir: redeem
  skip_cleanup: true
  cache_control: "max-age=300"
  on:
    branch: master
after_deploy:
  - aws configure set preview.cloudfront true
  - test $TRAVIS_BRANCH = "master" && aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/redeem/*"

